name: Snake 

on:
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./profile-snake-contrib/github-contribution-grid-snake.svg
            ./profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          target_branch: main
          build_dir: ./
          keep_history: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
